### ISSUE TITLE
[Bug] Command /setcolor does not work

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#35]
### Description

When using the command `/setcolor <channel> <color>` the color of the messages are not changed.

The message returns the channel name with the specified color but messages still use the default channel color.
![image](https://user-images.githubusercontent.com/51332006/91108601-c844a180-e64e-11ea-977a-9eae5fde634c.png)

Tab completer suggests channels instead of colors.
![image](https://user-images.githubusercontent.com/51332006/91108792-53259c00-e64f-11ea-93be-609ae6379bfa.png)

### How to reproduce

Use `/setcolor <channel> <color>`
Exemple: `/setcolor global red`

### config.yml

```yml
channels:
  global:
    name: 'Global'
    aliases: 'global|g'
    formats:
      default: '&2[g] %javascript_tag%%simpleclans_tag_label%&f<displayname>&7» <color><message>'
    message-prefix: '!'
    ignorable: true
   color: '#FFFFFF'
```
