### ISSUE TITLE
[Feature] Aliases for message and replay

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#36]
### Suggestion

- Add possibility to register aliases for private message and reply.
- Suggest list of online players in the first subcommand and then do not make any suggestions.
![image](https://user-images.githubusercontent.com/51332006/91127716-3a33df80-e67d-11ea-92b5-d1cb002ccc82.png)

Exemple:
```yml
private-message:
  aliases: 't|tell|m|pm'
reply:
  aliases: 'r'
```
