### ISSUE TITLE
[Bug] blocked-words from moderation.yml does not work

### ISSUE THREAD

**Issue by SrBedrock** [Hexaoxide/Carbon#40]
### Description

Messages sent in the chat containing the word specified in the configuration `blocked-words` are not blocked.

### How to reproduce

1. Add a word in the configuration;

```yml
filters:
  enabled: true
  case-sensitive: false
  filters:
  [...]
  # Anything in blocked-words will prevent the message from being sent at all.
  blocked-words:
      - "teste"
```

2. Restart the server;

3. Send the word in chat.

![image](https://user-images.githubusercontent.com/51332006/91279891-7427e300-e75c-11ea-9342-3f6fca3b13c2.png)
