### ISSUE TITLE
[Feature] Format placeholders

### ISSUE THREAD

**Issue by Draycia** [Hexaoxide/Carbon#73]
```yml
formats:
  default: "<prefix> <name><gray>: <white><message>"

placeholders:
  prefix: "<gray>[<group><gray>]"
  group: "<green>%vault_group%"
  name: "<white>%vault_nickname%"
```
